// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:487524253907:web:997b69bef510e347ec5426',
    messagingSenderId: '487524253907',
    projectId: 'my-firebase-19930026',
    authDomain: 'my-firebase-19930026.firebaseapp.com',
    storageBucket: 'my-firebase-19930026.firebasestorage.app',
    measurementId: 'G-H8GMHW5XMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:487524253907:android:1389df45ee069e58ec5426',
    messagingSenderId: '487524253907',
    projectId: 'my-firebase-19930026',
    storageBucket: 'my-firebase-19930026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:487524253907:ios:25a3452c9945fea5ec5426',
    messagingSenderId: '487524253907',
    projectId: 'my-firebase-19930026',
    storageBucket: 'my-firebase-19930026.firebasestorage.app',
    iosBundleId: 'com.example.reproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxF9fgrTaRfLqDzy-b5tY_DdIZe09UwcA',
    appId: '1:487524253907:ios:25a3452c9945fea5ec5426',
    messagingSenderId: '487524253907',
    projectId: 'my-firebase-19930026',
    storageBucket: 'my-firebase-19930026.firebasestorage.app',
    iosBundleId: 'com.example.reproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCihkBMDda4Ueb4acrd7DswtRHGVFcvmmA',
    appId: '1:487524253907:web:602a21d21d173353ec5426',
    messagingSenderId: '487524253907',
    projectId: 'my-firebase-19930026',
    authDomain: 'my-firebase-19930026.firebaseapp.com',
    storageBucket: 'my-firebase-19930026.firebasestorage.app',
    measurementId: 'G-PNQYDMPWWJ',
  );
}
